export const Subject = {
  All: 'all',
  User: 'User',
  UserHighlight: 'UserHighlight',
  TextToSpeech: 'TextToSpeech',
  ReadingProgress: 'ReadingProgress',
  ReadingList: 'ReadingList',
  Collection: 'Collection',
  Genre: 'Genre',
  Role: 'Role',
  Follow: 'Follow',
  Review: 'Review',
  ToxicWord: 'ToxicWord',
  Comment: 'Comment',
  Bookmark: 'Bookmark',
  AIRequest: 'AIRequest',
  UserPreference: 'UserPreference',
  UserEvent: 'UserEvent',
  RoomMember: 'RoomMember',
  ReadingRoom: 'ReadingRoom',
  Author: 'Author',
  Book: 'Book',
  VectorDocument: 'VectorDocument',
  SearchQuery: 'SearchQuery',
  Like: 'Like',
  Chapter: 'Chapter',
  ChapterKnowledge: 'ChapterKnowledge',
  RoomComment: 'RoomComment',
  RoomQuote: 'RoomQuote',
  RoomReaction: 'RoomReaction',
  Post: 'Post',
  Otp: 'Otp',
  Notification: 'Notification',
} as const;

export type AppSubject = (typeof Subject)[keyof typeof Subject];