import './globals.css';
import ScrollToTop from '../components/ScrollToTop';
import { Providers } from '../context/Providers';
import { Toaster } from 'sonner';
import AuthSync from '../components/AuthSync';
import { inter, merriweather, notoSans } from '@/src/components/book/Fonts';

export const metadata = {
  title: 'SocialBook',
  description: 'Generated by Anh em cây khế',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" className={`${inter.variable} ${merriweather.variable} ${notoSans.variable} mdl-js`} suppressHydrationWarning>
      <body>
        <Providers>
          <ScrollToTop />
          <AuthSync />
          {children}
        </Providers>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
