import './globals.css';
import { Providers } from '../context/Providers';
import { Header } from '../components/header';
import { Toaster } from 'sonner';

export const metadata = {
  title: 'SocialBook',
  description: 'Generated by Anh em cây khế',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" className="mdl-js">
      <body>
        <Header />
        <Providers>{children}</Providers>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
