import ''./globals.css';'
import { Providers } from '@/providers/providers';
import { Header } from '@/components/header';

export const metadata = {
  title: "SocialBook",
  description: "Generated by Anh em cây khế",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" className="mdl-js">
      <body>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
