import { Injectable, Logger } from '@nestjs/common';
import { IAuthorRepository } from '@/domain/authors/repositories/author.repository.interface';
import { IBookRepository } from '@/domain/books/repositories/book.repository.interface';
import { IVectorRepository } from '@/domain/chroma/repositories/vector.repository.interface';
import { VectorDocument } from '@/domain/chroma/entities/vector-document.entity';
import { IIdGenerator } from '@/shared/domain/id-generator.interface';

interface IndexStats {
  total: number;
  successful: number;
  failed: number;
  errors: string[];
}

export interface ReindexResult {
  success: boolean;
  message: string;
  details?: { authors: IndexStats; books: IndexStats };
}

@Injectable()
export class ReindexAllUseCase {
  private readonly logger = new Logger(ReindexAllUseCase.name);

  constructor(
    private readonly authorRepository: IAuthorRepository,
    private readonly bookRepository: IBookRepository,
    private readonly vectorRepository: IVectorRepository,
    private readonly idGenerator: IIdGenerator,
  ) {}

  async execute(): Promise<ReindexResult> {
    try {
      this.logger.log('🚀 Starting full reindexing process...');

      // 1. Clear existing collection
      this.logger.log('🧹 Clearing existing vector collection...');
      await this.vectorRepository.clearCollection();

      // 2. Reindex Authors
      const authorResults = await this.reindexAuthors();

      // 3. Reindex Books
      const bookResults = await this.reindexBooks();

      this.logger.log('✅ Full reindexing completed successfully');

      return {
        success: true,
        message: 'Reindexing completed successfully',
        details: {
          authors: authorResults,
          books: bookResults,
        },
      };
    } catch (error) {
      this.logger.error('❌ Reindexing failed', error);
      return {
        success: false,
        message: `Reindexing failed: ${error.message}`,
      };
    }
  }

  private async reindexAuthors() {
    this.logger.log('📚 Reindexing authors...');
    const authors = await this.authorRepository.findAllSimple();

    let successful = 0;
    let failed = 0;
    const errors: string[] = [];

    for (const author of authors) {
      try {
        const content = `Tác giả: ${author.name.toString()}\nTiểu sử: ${author.bio}`;

        const document = VectorDocument.createAuthorDocument(
          this.idGenerator.generate(),
          author.id.toString(),
          content,
          {
            name: author.name.toString(),
            slug: author.slug,
            photoUrl: author.photoUrl,
          },
          [], // Embedding will be generated by the vector store
        );

        await this.vectorRepository.save(document);
        successful++;
      } catch (error) {
        this.logger.error(`Failed to index author ${author.id.toString()}: ${error.message}`);
        errors.push(`${author.id.toString()}: ${error.message}`);
        failed++;
      }
    }

    this.logger.log(`📊 Author indexing completed: ${successful} successful, ${failed} failed`);
    
    return {
      total: authors.length,
      successful,
      failed,
      errors: errors.slice(0, 10), // Return first 10 errors
    };
  }

  private async reindexBooks() {
    this.logger.log('📖 Fetching all books from database...');
    const result = await this.bookRepository.findAll({}, { page: 1, limit: 2000 });
    const books = result.data;
    this.logger.log(`📖 Found ${books.length} books to index. Starting...`);

    let successful = 0;
    let failed = 0;
    const errors: string[] = [];
    const PROGRESS_INTERVAL = 5; // Log mỗi 5 cuốn

    for (let i = 0; i < books.length; i++) {
      const book = books[i];
      try {
        const titleStr = book.title.toString();
        const authorStr = book.authorName || 'Không rõ tác giả';
        const genreStr = book.genreObjects?.map(g => g.name).join(', ') || '';
        const tagStr = book.tags?.length > 0 ? book.tags.join(', ') : '';

        // 1. Index Main Document (Title + Author + Genres + Tags) — HIGH IMPORTANCE
        const mainParts = [`Tên sách: ${titleStr}`, `Tác giả: ${authorStr}`];
        if (genreStr) mainParts.push(`Thể loại: ${genreStr}`);
        if (tagStr) mainParts.push(`Từ khóa: ${tagStr}`);
        const mainContent = mainParts.join('\n');

        const mainDoc = VectorDocument.createBookDocument(
          this.idGenerator.generate(),
          book.id.toString(),
          mainContent,
          {
            title: titleStr,
            slug: book.slug,
            authorName: authorStr,
            coverUrl: book.coverUrl,
            type: 'main',
          },
          [],
        );
        await this.vectorRepository.save(mainDoc);

        // 2. Index Description Chunks
        const descriptionChunks = this.chunkText(book.description);
        for (const chunk of descriptionChunks) {
          const chunkContent = `Tên sách: ${titleStr}\nThể loại: ${genreStr}\nMô tả: ${chunk}`;
          const chunkDoc = VectorDocument.createBookDocument(
            this.idGenerator.generate(),
            book.id.toString(),
            chunkContent,
            {
              title: titleStr,
              slug: book.slug,
              authorName: authorStr,
              coverUrl: book.coverUrl,
              type: 'excerpt',
            },
            [],
          );
          await this.vectorRepository.save(chunkDoc);
        }

        successful++;

        // Log tiến trình mỗi PROGRESS_INTERVAL cuốn
        if ((i + 1) % PROGRESS_INTERVAL === 0 || i + 1 === books.length) {
          const pct = Math.round(((i + 1) / books.length) * 100);
          this.logger.log(
            `📖 [${i + 1}/${books.length}] ${pct}% — "${titleStr}" ✅ (${descriptionChunks.length} chunks)`,
          );
        }
      } catch (error) {
        this.logger.error(
          `[${i + 1}/${books.length}] ❌ Failed: "${book.title}" — ${error.message}`,
        );
        errors.push(`${book.id.toString()}: ${error.message}`);
        failed++;
      }
    }

    this.logger.log(`📊 Book indexing completed: ${successful}/${books.length} successful, ${failed} failed`);

    return {
      total: books.length,
      successful,
      failed,
      errors: errors.slice(0, 10),
    };
  }

  private chunkText(text: string): string[] {
    if (!text || text.trim().length === 0) return [];
    
    // Split by sentence terminators
    const sentences = text
      .split(/[.!?]+\s+/)
      .map(s => s.trim())
      .filter(s => s.length > 0);
    
    const chunks: string[] = [];
    const GROUP_SIZE = 3;

    for (let i = 0; i < sentences.length; i += GROUP_SIZE) {
      const group = sentences.slice(i, i + GROUP_SIZE);
      chunks.push(group.join('. ') + '.');
    }
    
    return chunks;
  }
}
