export enum UserEventType {
  OPEN_BOOK = 'open_book',
  START_READING = 'start_reading',
  READING_PROGRESS = 'reading_progress',
  FINISH_CHAPTER = 'finish_chapter',
  FINISH_BOOK = 'finish_book',
  LIKE_BOOK = 'like_book',
  BOOKMARK_BOOK = 'bookmark_book',
  COMMENT_BOOK = 'comment_book',
  SHARE_BOOK = 'share_book',
  RATE_BOOK = 'rate_book',
  CLOSE_BOOK_EARLY = 'close_book_early',
  SKIP_BOOK = 'skip_book',
  DISLIKE_BOOK = 'dislike_book',
  SEARCH = 'search',
  IMPRESSION = 'impression',
  CLICK_RECOMMENDATION = 'click_recommendation',
}
