export type {
  Post,
  RawPost,
  PostAuthor,
  PostBook,
  CreatePostRequest,
  UpdatePostRequest,
  DeleteImageRequest,
  PaginatedPostsResponse,
  PaginationParams,
  PaginationParamsByUser,
  PostWithModerationResult,
  TrendingBook,
  TopReader,
} from '@/features/posts/schemas/post.schema';