import type { Author } from '@/features/authors/types/author.interface';
import type { Genre } from '@/features/genres/types/genre.interface';
export type { Author, Genre };

export {
  BOOK_STATUS,
  bookStatusSchema,
  type BookStatus,
  authorRefSchema,
  type AuthorRef,
  genreSummarySchema,
  type GenreSummary,
  bookStatsSchema,
  type BookStats,
  bookSummarySchema,
  type BookSummary,
  bookChapterSchema,
  type BookChapter,
  bookDetailSchema,
  type BookDetail,
  type Book,
  bookAdminSchema,
  type BookForAdmin,
  paginationMetaSchema,
  type PaginationMetaData,
  bookSummaryPageSchema,
  type BookSummaryPage,
  bookAdminPageSchema,
  type AdminBooksData,
  filtersDataSchema,
  type FiltersData,
  likeResultSchema,
  type LikeResult,
  bookViewStatsSchema,
  type BookViewStats,
  BOOK_ORDER_FIELD,
  type BookOrderField,
  type GetBookParams,
  type GetBooksParams,
  type GetAdminBooksParams,
  type UpdateBookParams,
  type BackendPagination,
  type PaginatedData,
  type TabState,
  type TabStates,
} from '../schemas/book.schema';