export const books = [
  {
    id: '1',
    title: 'Thế Giới Phép Thuật',
    slug: 'the-gioi-phep-thuat',
    author: 'Nguyễn Văn A',
    cover: '/fantasy-magic-world-book-cover.jpg',
    rating: 4.8,
    reads: '2.1M',
    genre: 'Fantasy',
    description:
      'Một thế giới đầy phép thuật và những cuộc phiêu lưu kỳ thú đang chờ đón bạn...',
    isNew: true,
    isTrending: true,
  },
  {
    id: '2',
    title: 'Tình Yêu Tuổi 17',
    slug: 'tinh-yeu-tuoi-17',
    author: 'Trần Thị B',
    cover: '/teen-romance-book-cover.jpg',
    rating: 4.9,
    reads: '1.8M',
    genre: 'Romance',
    description:
      'Câu chuyện tình yêu ngọt ngào của tuổi học trò với những cung bậc cảm xúc...',
    isNew: false,
    isTrending: true,
  },
  {
    id: '3',
    title: 'Kiếm Hiệp Giang Hồ',
    slug: 'kiem-hiep-giang-ho',
    author: 'Lê Văn C',
    cover: '/martial-arts-swordsman-book.jpg',
    rating: 4.7,
    reads: '1.5M',
    genre: 'Võ hiệp',
    description:
      'Hành trình trở thành cao thủ võ lâm của một chàng trai trẻ...',
    isNew: true,
    isTrending: false,
  },
  {
    id: '4',
    title: 'Bí Ẩn Thành Phố',
    slug: 'bi-an-thanh-pho',
    author: 'Phạm Thị D',
    cover: '/mystery-city-detective-book.jpg',
    rating: 4.6,
    reads: '1.2M',
    genre: 'Mystery',
    description:
      'Những vụ án bí ẩn trong thành phố lớn và cuộc truy tìm sự thật...',
    isNew: false,
    isTrending: true,
  },
  {
    id: '5',
    title: 'Công Chúa Rồng',
    slug: 'cong-chua-rong',
    author: 'Hoàng Văn E',
    cover: '/dragon-princess-fantasy-book.jpg',
    rating: 4.8,
    reads: '980K',
    genre: 'Fantasy',
    description:
      'Cuộc phiêu lưu của công chúa rồng trong thế giới thần thoại...',
    isNew: true,
    isTrending: false,
  },
];
