export const posts = [
    {
        id: '6911b0a53ff60a8639bb8509',
        userId: 'u1',
        userName: 'Nguyễn Văn A',
        userAvatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        bookId: '1',
        bookTitle: 'Thế Giới Phép Thuật',
        content:
            '“Thế giới phép thuật thật sự quá tuyệt vời! Tôi thích cách tác giả tạo ra từng chi tiết của thế giới này.” ✨',
        image: ['/detective-mystery-city-book-cover.jpg'],
        isDelete: false,
        createdAt: new Date('2025-11-10T09:30:15Z'),
        totalLikes: 124,
        totalComments: 8,
        likedByCurrentUser: true,
        comments: [
            {
                userName: 'Lê Hoàng',
                userAvatar: 'https://i.pravatar.cc/150?img=12',
                content: 'Công nhận! Mình cũng mê thế giới phép thuật này lắm 🪄',
                createdAt: '2 giờ trước',
            },
            {
                userName: 'Trần Mai',
                userAvatar: 'https://i.pravatar.cc/150?img=25',
                content: 'Tác giả viết mượt thật, đọc cuốn không dừng được 😍',
                createdAt: '1 giờ trước',
            },
            {
                userName: 'Ngọc Anh',
                userAvatar: 'https://i.pravatar.cc/150?img=36',
                content: 'Cảnh chiến đấu ở chương 10 đỉnh quá trời 🔥🔥',
                createdAt: '45 phút trước',
            },
        ],
    },
    {
        id: '6911b0a73ff60a8639bb850b',
        userId: 'u2',
        userName: 'Trần Thị B',
        userAvatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        bookId: '2',
        bookTitle: 'Tình Yêu Tuổi 17',
        content:
            'Câu chuyện tình yêu tuổi học trò thật sự khiến tôi nhớ lại những năm tháng ngây ngô 😍',
        image: ['/dragon-princess-fantasy-book.jpg'],
        isDelete: false,
        createdAt: new Date('2025-11-09T14:25:00Z'),
        totalLikes: 200,
        totalComments: 15,
        likedByCurrentUser: false,
        comments: [
            {
                userName: 'Tuấn Kiệt',
                userAvatar: 'https://i.pravatar.cc/150?img=14',
                content: 'Đọc xong tự nhiên nhớ crush cấp 3 🥹',
                createdAt: '3 giờ trước',
            },
            {
                userName: 'Phương Linh',
                userAvatar: 'https://i.pravatar.cc/150?img=9',
                content: 'Nhân vật chính dễ thương quá trời 💕',
                createdAt: '2 giờ trước',
            },
            {
                userName: 'Duy Tân',
                userAvatar: 'https://i.pravatar.cc/150?img=33',
                content: 'Cảm xúc y chang mình hồi đi học 😄',
                createdAt: '1 giờ trước',
            },
        ],
    },
    {
        id: 'p3',
        userId: 'u3',
        userName: 'Lê Văn C',
        userAvatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        bookId: '3',
        bookTitle: 'Kiếm Hiệp Giang Hồ',
        content:
            'Một chàng trai bình thường trở thành cao thủ võ lâm — đúng kiểu truyện tôi mê từ nhỏ! 🥋🔥',
        image: ['/fantasy-magic-world-book-cover.jpg'],
        isDelete: false,
        createdAt: new Date('2025-11-08T18:42:10Z'),
        totalLikes: 89,
        totalComments: 4,
        likedByCurrentUser: false,
        comments: [
            {
                userName: 'Hải Nam',
                userAvatar: 'https://i.pravatar.cc/150?img=17',
                content: 'Đọc mà cảm giác như đang xem phim kiếm hiệp luôn 😎',
                createdAt: '30 phút trước',
            },
            {
                userName: 'Phúc Hậu',
                userAvatar: 'https://i.pravatar.cc/150?img=41',
                content: 'Tác giả viết võ công chi tiết, đọc cuốn hút cực 💪',
                createdAt: '10 phút trước',
            },
        ],
    },
    {
        id: 'p4',
        userId: 'u4',
        userName: 'Phạm Thị D',
        userAvatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        bookId: '4',
        bookTitle: 'Bí Ẩn Thành Phố',
        content:
            'Câu chuyện trinh thám “Bí Ẩn Thành Phố” khiến tôi đọc liền một mạch! Ai là hung thủ đây? 🕵️‍♂️',
        image: ['/ice-princess-fantasy-book-cover.jpg'],
        isDelete: false,
        createdAt: new Date('2025-11-07T11:10:00Z'),
        totalLikes: 312,
        totalComments: 27,
        likedByCurrentUser: true,
        comments: [
            {
                userName: 'Thu Trang',
                userAvatar: 'https://i.pravatar.cc/150?img=45',
                content: 'Plot twist cuối truyện làm mình nổi da gà 😱',
                createdAt: '1 ngày trước',
            },
            {
                userName: 'Minh Đức',
                userAvatar: 'https://i.pravatar.cc/150?img=28',
                content: 'Cảm giác như đang xem Sherlock Holmes bản Việt 🔎',
                createdAt: '22 giờ trước',
            },
        ],
    },
    {
        id: 'p5',
        userId: 'u5',
        userName: 'Hoàng Văn E',
        userAvatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        bookId: '5',
        bookTitle: 'Công Chúa Rồng',
        content:
            '“Công Chúa Rồng” thật sự là một hành trình tuyệt đẹp, vừa hoành tráng vừa cảm động 🐉❤️',
        image: ['/legendary-swordsman-martial-arts-book.jpg'],
        isDelete: false,
        createdAt: new Date('2025-11-06T08:50:00Z'),
        totalLikes: 178,
        totalComments: 10,
        likedByCurrentUser: false,
        comments: [
            {
                userName: 'Hồng Nhung',
                userAvatar: 'https://i.pravatar.cc/150?img=56',
                content: 'Công chúa dũng cảm và đáng yêu quá 😍',
                createdAt: '3 giờ trước',
            },
            {
                userName: 'Bảo Long',
                userAvatar: 'https://i.pravatar.cc/150?img=64',
                content: 'Mình thích mạch truyện kết hợp giữa phép thuật và cảm xúc ❤️‍🔥',
                createdAt: '1 giờ trước',
            },
        ],
    },
];
