export const posts = [
    {
        id: 'p1',
        userId: 'u1',
        userName: 'Nguyễn Văn A',
        userAvatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        bookId: '1',
        bookTitle: 'Thế Giới Phép Thuật',
        content:
            '“Thế giới phép thuật thật sự quá tuyệt vời! Tôi thích cách tác giả tạo ra từng chi tiết của thế giới này.” ✨',
        image: ['/detective-mystery-city-book-cover.jpg'],
        isDelete: false,
        createdAt: new Date('2025-11-10T09:30:15Z'),
        totalLikes: 124,
        totalComments: 8,
        likedByCurrentUser: true,
    },
    {
        id: 'p2',
        userId: 'u2',
        userName: 'Trần Thị B',
        userAvatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        bookId: '2',
        bookTitle: 'Tình Yêu Tuổi 17',
        content:
            'Câu chuyện tình yêu tuổi học trò thật sự khiến tôi nhớ lại những năm tháng ngây ngô 😍',
        image: ['/dragon-princess-fantasy-book.jpg'],
        isDelete: false,
        createdAt: new Date('2025-11-09T14:25:00Z'),
        totalLikes: 200,
        totalComments: 15,
        likedByCurrentUser: false,
    },
    {
        id: 'p3',
        userId: 'u3',
        userName: 'Lê Văn C',
        userAvatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        bookId: '3',
        bookTitle: 'Kiếm Hiệp Giang Hồ',
        content:
            'Một chàng trai bình thường trở thành cao thủ võ lâm — đúng kiểu truyện tôi mê từ nhỏ! 🥋🔥',
        image: ['/fantasy-magic-world-book-cover.jpg'],
        isDelete: false,
        createdAt: new Date('2025-11-08T18:42:10Z'),
        totalLikes: 89,
        totalComments: 4,
        likedByCurrentUser: false,
    },
    {
        id: 'p4',
        userId: 'u4',
        userName: 'Phạm Thị D',
        userAvatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        bookId: '4',
        bookTitle: 'Bí Ẩn Thành Phố',
        content:
            'Câu chuyện trinh thám “Bí Ẩn Thành Phố” khiến tôi đọc liền một mạch! Ai là hung thủ đây? 🕵️‍♂️',
        image: ['/ice-princess-fantasy-book-cover.jpg'],
        isDelete: false,
        createdAt: new Date('2025-11-07T11:10:00Z'),
        totalLikes: 312,
        totalComments: 27,
        likedByCurrentUser: true,
    },
    {
        id: 'p5',
        userId: 'u5',
        userName: 'Hoàng Văn E',
        userAvatar: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70)}`,
        bookId: '5',
        bookTitle: 'Công Chúa Rồng',
        content:
            '“Công Chúa Rồng” thật sự là một hành trình tuyệt đẹp, vừa hoành tráng vừa cảm động 🐉❤️',
        image: ['/legendary-swordsman-martial-arts-book.jpg'],
        isDelete: false,
        createdAt: new Date('2025-11-06T08:50:00Z'),
        totalLikes: 178,
        totalComments: 10,
        likedByCurrentUser: false,
    },
];
